services:
  jellyfin-vote:
    build: .
    container_name: jellyfin-vote
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
    environment:
      # URL deines Jellyfin-Servers anpassen!
      - JELLYFIN_URL=http://YOUR_JELLYFIN_IP:8096
      # Name der Webseite (frei waehlbar)
      - SITE_NAME=Jellyfin Vote
      - PORT=3000
