services:
  chrisflix-vote:
    build: .
    container_name: chrisflix-vote
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
    environment:
      # URL deines Jellyfin-Servers anpassen!
      - JELLYFIN_URL=http://YOUR_JELLYFIN_IP:8096
      - PORT=3000
